//import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './auth/Nav'
//import { Roboto } from '@next/font/google'

// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   variable: "--font-roboto",
// })

const inter = Inter({
  subsets: ['latin'],
  weights: ['400', '700'], // Adjust the weights as needed
  variable: '--font-inter', // Customize the variable name as required
  // Add any additional options here if necessary
});

//const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={`mx-4 md:mx-48 xl:mx-96 ${inter.className} bg-gray-200`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head />
//       <body className={`mx-4 md:mx-48 xl:mx-96 ${roboto.className} bg-gray-200`}>
//         <Nav />
//         {children}
//       </body>
//     </html>
//   );
// }